image: Visual Studio 2017

clone_depth: 3

install:
  - dotnet restore

build_script:
  - ps: .\build.ps1

 test_script:
  - ps: .\test.ps1
  
artifacts:
  - path: src\Norgerman.Cryptography.Scrypt\bin\**\*.nupkg
    name: Norgerman.Cryptography.Scrypt  
    
deploy:
  provider: NuGet
  api_key:
    secure: RibWaT8a9QpArRhQVG/Ibr6fx3/UubrxnrRre8QSJPvt0pLhuoDJe6/GJX4lyi2S
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true
