image: Visual Studio 2017

clone_depth: 3

install:
 - curl -O https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-x64.exe
 - dotnet-sdk-2.0.0-win-x64.exe /install /quiet /norestart /log install.log
 - dotnet restore

build_script:
  - ps: .\build.ps1

test_script:
  - ps: .\test.ps1
  
artifacts:
  - path: src\Norgerman.Cryptography.Scrypt\bin\**\*.nupkg
    name: Norgerman.Cryptography.Scrypt  
    
deploy:
  provider: NuGet
  api_key:
    secure: RibWaT8a9QpArRhQVG/Ibr6fx3/UubrxnrRre8QSJPvt0pLhuoDJe6/GJX4lyi2S
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true
