image: Visual Studio 2017

platform: 
  - x86
  - x64

clone_depth: 3

build_script:
  - ps: .\build.ps1
  - ps: .\test.ps1

artifacts:
  - path: src\Norgerman.Cryptography.Scrypt\bin\**\*.nupkg
    name: Norgerman.Cryptography.Scrypt
    
test: off
    
deploy:
  provider: NuGet
  api_key:
    secure: RibWaT8a9QpArRhQVG/Ibr6fx3/UubrxnrRre8QSJPvt0pLhuoDJe6/GJX4lyi2S
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true