on:
  push:
  pull_request:
    branches:
      - master
      - dev

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - run: dotnet build
      - run: dotnet test test/Norgerman.Cryptography.Scrypt.Test -c Release
