on:
  release:
    types: [published]

name: Publish release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup dotnet for nuget
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      - run: dotnet pack -c Release src/Norgerman.Cryptography.Scrypt
      - shell: bash
        env:
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        run: dotnet nuget push src/Norgerman.Cryptography.Scrypt/bin/Release/*.nupkg --skip-duplicate -k ${NUGET_API_KEY}

      - name: Setup dotnet for github
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/Norgerman/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet nuget push src/Norgerman.Cryptography.Scrypt/bin/Release/*.nupkg --skip-duplicate
